version: '3'
services:
       
    swagger:
        image: "swaggerapi/swagger-ui"
        networks: 
            - ml
        ports:
            - "4400:8080"
        environment: 
            BASE_URL: /swagger 
            SWAGGER_JSON: /swagger.json
            VIRTUAL_HOST: ml.swagger
            VIRTUAL_PORT: 4400
        volumes:
            - ./swagger/mlcloud.json:/swagger.json        
                    
networks:
    ml:
              
